apiVersion: v1
baseDomain: kcb.home
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
fips: false
platform: 
  none: {}
pullSecret: '{"auths":{"bastion.okd4.kcb.home:5000":{"auth":"YWRtaW46b3Blbm5hcnU="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVCuvOx3tBzCg3Xt1f4LIDBCX+S9qOpPfZ9hhaiWxtHELISvUn5NOpGX1EToNoxuUOtrT3EZ4YGsycKFN1UqYmu62+Zai3AJXn5kkgk5JpKrdoGBFUE33lB4RBLKOSdcQuOiJbhzeaphCz5TiLQb7BftHIQeRQgJyvT00tHN5LgL/ANQMjRTcHnHLAZlUOBxyYgZCprP+2m5TfHrudo3IGOlouVBtbCZuwdVm0IMX274S2R4Mtfx2culg5jPgTQIewwXxYyWz5o4nEdzkzI5GMxF+i25ZnntYakTKmt62hIcoGzOda5eGIl0V9X28NPjlp7nIYb8ksIKoViRCp8fIuRzh6Q+dXQI/KcKkg+aospdMd+Zn6LqCJu/bbtKo7HM4Gtat0o+RBoC8t5mhD3c8j5+zuv4ci/yVuTc+kryaHtyaEpYX5rG9mQTsMBXz9lqVz/iQ8Un7ubf7k9jRS3CiYGmg+KxfaM5TJUdJhpTZmeTGiE78L9e93wUhP9Ibk572p5OTpp/58UQVDWukNBAOV5PKeW6l8HasQJi3hxDOKq0p9dWWP+EwkJaLMb+6npsyWaJq4dZYk02LQv+uEbGqkqVBhHKeENRBqgKWj4SmUpGX/J4ofTBEz5zM75gFci/I/oazBLJmDjQKaiK38sm0hqVKBpjExD2kpqF7aZu9aMw== root@bastion.ocp4.kcb.home'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGNTCCBB2gAwIBAgIUdo+DUJEpUmhKOws1ZU46SO+Vm14wDQYJKoZIhvcNAQEL
  BQAwgZgxCzAJBgNVBAYTAktPMQ4wDAYDVQQIDAVTZW91bDEOMAwGA1UEBwwFU2Vv
  dWwxETAPBgNVBAoMCE9QRU5OQVJVMREwDwYDVQQLDAhPUEVOTkFSVTEeMBwGA1UE
  AwwVYmFzdGlvbi5va2Q0LmtjYi5ob21lMSMwIQYJKoZIhvcNAQkBFhRzdXBwb3J0
  QG9wZW5uYXJ1LmNvbTAeFw0yNDA0MDcwNjAxMTVaFw0zNDA0MDUwNjAxMTVaMIGY
  MQswCQYDVQQGEwJLTzEOMAwGA1UECAwFU2VvdWwxDjAMBgNVBAcMBVNlb3VsMREw
  DwYDVQQKDAhPUEVOTkFSVTERMA8GA1UECwwIT1BFTk5BUlUxHjAcBgNVBAMMFWJh
  c3Rpb24ub2tkNC5rY2IuaG9tZTEjMCEGCSqGSIb3DQEJARYUc3VwcG9ydEBvcGVu
  bmFydS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDT1ZFFO6xe
  iSbj5QqboSHyqlSZtQ1Fd0RyBtfeY9Q2ceHxK9LMydilNbZ8KH/Tabn1qNj0L2cV
  84Jx+l5tBP+IupY+cmm1RwfFYfO5AvXXgiYesCQS5aimxlYbkdy2GELHZvRP1Ron
  07m73dWmfrb3+oTcs7+2LdwakdamkW5pQFEhh2843VvepUIORNlxFHsKRiO2Z40q
  4BtIzUM+quUg+SvKncUtovLdBAOJmFJOcwPzdSaaoHCy0Nk7+b3TqOEJv0uuKY6u
  13Y66Aub18LSk35O86ddBasdsCAnmK/kmAl/fr8uEbUCGi9qSqlBBgfpCKAFHLP4
  BGeBQiPZi7VthX06XxBg0MD51MkgMeoNbI8G0jlieRCL9CBbe+OAUHKkQ8PdBcYT
  ANzkUksOtw0O+4z1sr++npRx3b02xmGRLN79z6jlQ7kdetV5ZZVrnzvl0NcOgi9d
  N6vbNE64ewEmsbHUgtxfBwJRHFwNjBK9dPu+ECflcvOrYMGr5yO7tRFxZsaeqBtc
  KZbg7nuTXUp6IBoJTTJ41AMG3Xy0MLKSmdqKjV9N8m8RpSiEyy7d0x+uAF4oP+NV
  AStaqdeCHYVxhSvoV2oo0jArspTYX2Ep2jW7xCoOu/JIN9aLTKAXkyrVF9K2y8OH
  uF6bNj3uzj1LtEAYOp+8T2GmoO5JngpzuQIDAQABo3UwczAdBgNVHQ4EFgQUdpVi
  EzreMzuVE0vwnL7YqVKEFGowHwYDVR0jBBgwFoAUdpViEzreMzuVE0vwnL7YqVKE
  FGowDwYDVR0TAQH/BAUwAwEB/zAgBgNVHREEGTAXghViYXN0aW9uLm9rZDQua2Ni
  LmhvbWUwDQYJKoZIhvcNAQELBQADggIBAKQjmH91VjnHvoD6Aw4u+iMbpy8p2Duj
  0s9iWWskhENLQZwXY/H9I6veOPJELYU32wAB792mumXi2lpSF23K8KS1ZX5bJFZC
  zxdozZURq7fMm7n6GhcaYin6c6kK/YPtkdZ5oAyr9bO3QYjVq/FIowto9Z2OjAsA
  UKypHIxeA3w98nhpV728UYzvTeZst8AK9e8jyRJgENRkwq52mMjddpOB4NJhVUFX
  ziQR/d3/NcRZqnNv2VuREyNORZOZm1MSQuc4jCMbE53frht7Y+Tt07NHLv8GIkcZ
  5DHBeTkdbrqMJm/GeDmY6SaSlYlUkBQiE8IlWvUYnmVxU77URx2BA379ANt/2dCn
  S9u1b5BdUUG5Iqilm9SEQ92l1e7CAKdP6o8rcsC6BDcxkCvyvQftI1KxPkL42D1T
  I0pyfSMEbSWHLthLlqCnSPBh0CpAMIcOGZO93V/q2JS67RSbUprCRWYZeMWEz/4G
  NPoa/p7WlW7xIzwAtvdT4ZrZ4mBVmw7KQP0mLIzifxbRslXCi5N4utsgk9sIEk1H
  tdGwZyVnBcADHLxgUk7w0Tah/Zl4gI8pLA+mKS3qiU5ghz/c95Fao53+PZRNw4Lj
  3CAd+LV+sC/XZkrOmr8aKsfF2N0odz6Bk9BmtO1C38N7VqAd+zm1zjlqjsANyaKe
  Ax8oLrj8jQin
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bastion.okd4.kcb.home:5000/okd4/release
  source: quay.io/openshift/okd
- mirrors:
  - bastion.okd4.kcb.home:5000/okd4/release
  source: quay.io/openshift/okd-content
